CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "CategoriasLibro" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "Descripcion" text NOT NULL,
    CONSTRAINT "PK_CategoriasLibro" PRIMARY KEY (id)
);

CREATE TABLE "Usuarios" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "Correo" text NOT NULL,
    "Password" text NOT NULL,
    CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id")
);

CREATE TABLE "Libros" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Titulo" text NOT NULL,
    "Autor" text NOT NULL,
    "Resumen" text NOT NULL,
    "CategoriasLibroId" bigint NOT NULL,
    CONSTRAINT "PK_Libros" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Libros_CategoriasLibro_CategoriasLibroId" FOREIGN KEY ("CategoriasLibroId") REFERENCES "CategoriasLibro" (id) ON DELETE CASCADE
);

CREATE TABLE "Reviews" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Calificacion" integer NOT NULL,
    "Comentario" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UsuarioId" bigint NOT NULL,
    "LibroId" bigint NOT NULL,
    CONSTRAINT "PK_Reviews" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Reviews_Libros_LibroId" FOREIGN KEY ("LibroId") REFERENCES "Libros" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Reviews_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Libros_CategoriasLibroId" ON "Libros" ("CategoriasLibroId");

CREATE INDEX "IX_Reviews_LibroId" ON "Reviews" ("LibroId");

CREATE INDEX "IX_Reviews_UsuarioId" ON "Reviews" ("UsuarioId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250125040836_InitialCreate', '6.0.36');

COMMIT;

START TRANSACTION;

ALTER TABLE "Usuarios" ADD "RefreshToken" text NOT NULL DEFAULT '';

ALTER TABLE "Usuarios" ADD "RefreshTokenExpiry" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250126022807_MigracionRefreshTokenUsuarios', '6.0.36');

COMMIT;

